In [1]:
import numpy as np

In [12]:
x =np.linspace(-0.5, 0.5, num=12).reshape(3, 4)

In [21]:
x/np.max(x, keepdims= True)

array([[-1.        , -0.81818182, -0.63636364, -0.45454545],
       [-0.27272727, -0.09090909,  0.09090909,  0.27272727],
       [ 0.45454545,  0.63636364,  0.81818182,  1.        ]])

In [26]:
(x>0) *x

array([[-0.        , -0.        , -0.        , -0.        ],
       [-0.        , -0.        ,  0.04545455,  0.13636364],
       [ 0.22727273,  0.31818182,  0.40909091,  0.5       ]])

In [29]:
[x for x in xrange(5)]

[0, 1, 2, 3, 4]

In [31]:
[x for x in range(5)]

[0, 1, 2, 3, 4]

In [35]:
x = {'a' : 1, 'b' : 2, 'c': (1,2,3)}
x.keys()

['a', 'c', 'b']

In [41]:
1/float(4) * np.ones([2,3])

array([[ 0.25,  0.25,  0.25],
       [ 0.25,  0.25,  0.25]])

In [129]:
(np.random.random([2,2]) < 0.8)

array([[False,  True],
       [ True,  True]], dtype=bool)

In [142]:
A = np.array([[1,2,3,4,5],[1,2,3,4,5]])

In [144]:
np.pad(A, ((2,),(2,)), 'constant')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 4, 5, 0, 0],
       [0, 0, 1, 2, 3, 4, 5, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])