In [1]:
import numpy as np

In [2]:
x = np.array([[1,2,3], [2,3,4],[5,6,7]])
y = np.array([[7,8,9],[9,10,11]])

In [3]:

def compute_distances_two_loops(Y, X):
    """
    Compute the distance between each test point in X and each training point
    in self.X_train using a nested loop over both the training data and the 
    test data.

    Inputs:
    - X: A numpy array of shape (num_test, D) containing test data.

    Returns:
    - dists: A numpy array of shape (num_test, num_train) where dists[i, j]
      is the Euclidean distance between the ith test point and the jth training
      point.
    """
    num_test = X.shape[0]
    num_train = Y.shape[0]
    dists = np.zeros((num_test, num_train))
    for i in xrange(num_test):
      for j in xrange(num_train):
        #####################################################################
        # TODO:                                                             #
        # Compute the l2 distance between the ith test point and the jth    #
        # training point, and store the result in dists[i, j]. You should   #
        # not use a loop over dimension.                                    #
        #####################################################################
          sqare_dist = np.abs(X[i , :] - Y[j , :])
          dists[i, j] = float(sqare_dist.sum)
        #####################################################################
        #                       END OF YOUR CODE                            #
        #####################################################################
    return dists

In [4]:
num_test = y.shape[0]
num_train = x.shape[0]
dists = np.zeros((num_test, num_train))
dists

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [5]:
for i in xrange(num_test):
      for j in xrange(num_train):
        #####################################################################
        # TODO:                                                             #
        # Compute the l2 distance between the ith test point and the jth    #
        # training point, and store the result in dists[i, j]. You should   #
        # not use a loop over dimension.                                    #
        #####################################################################
        sqare_dist = (y[i , :] - x[j , :]) ** 2
        dists[i,j] = np.sqrt(np.sum(sqare_dist))
print dists

[[ 10.39230485   8.66025404   3.46410162]
 [ 13.85640646  12.12435565   6.92820323]]


In [6]:
dists.argsort()[:, np.array([1,0])]

array([[1, 2],
       [1, 2]])

In [7]:
for i in xrange(num_test):
  #######################################################################
  # TODO:                                                               #
  # Compute the l2 distance between the ith test point and all training #
  # points, and store the result in dists[i, :].                        #
  #######################################################################
  sqare_dist = (x - y[i , :]) ** 2
  dists[i, :] = np.sqrt(np.sum(sqare_dist, axis=1))
  #######################################################################
  #                         END OF YOUR CODE                            #
  #######################################################################
print dists

[[ 10.39230485   8.66025404   3.46410162]
 [ 13.85640646  12.12435565   6.92820323]]


In [8]:
print np.sum(x **2 , axis= 1)
print  np.sum(y **2 , axis= 1).reshape(2, -1)
print np.sum(x **2 , axis= 1) + np.sum(y **2 , axis= 1).reshape(-1, 1)

[ 14  29 110]
[[194]
 [302]]
[[208 223 304]
 [316 331 412]]


In [9]:
np.sum(x[0] == y[0])

0

In [15]:
x[0][2] - (7 == y[0,0])

2